// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2J13lYGbsUvox11ZTpLrWLAXFcFuIgSQ',
    appId: '1:151996312316:web:6e833e5df9a76645c4c579',
    messagingSenderId: '151996312316',
    projectId: 'sweet-cake-warsaw-00',
    authDomain: 'sweet-cake-warsaw-00.firebaseapp.com',
    storageBucket: 'sweet-cake-warsaw-00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChi7Er9Ouf_YY0L-hC4rgxtxvepx0tfE8',
    appId: '1:151996312316:android:c0028b7157075dddc4c579',
    messagingSenderId: '151996312316',
    projectId: 'sweet-cake-warsaw-00',
    storageBucket: 'sweet-cake-warsaw-00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjOs8AFa_BPXaLcZTPWBAjJ01AqbQEoRE',
    appId: '1:151996312316:ios:b2183971e433fde2c4c579',
    messagingSenderId: '151996312316',
    projectId: 'sweet-cake-warsaw-00',
    storageBucket: 'sweet-cake-warsaw-00.appspot.com',
    iosClientId: '151996312316-1f188eag5u1dqn4kd1vsb19fm319ragf.apps.googleusercontent.com',
    iosBundleId: 'com.martaczech.sweetCakeWarsaw',
  );
}
